services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn food_ordering_backend.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: твой_секрет
